services:
  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./telemetry_output:/app/telemetry_output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  application:
    build: ./application
    ports:
      - "8080:8080" # Map Node.js app's port 8080 to host's port 8080
    environment:
      # OTLP endpoint for the collector. 'otel-collector' is the service name in the Docker network.
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      # Resource attributes for your Node.js service
      OTEL_RESOURCE_ATTRIBUTES: service.name=node-dice-app,deployment.environment=development
    depends_on:
      - otel-collector # Ensures the collector starts before the Node.js app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"