receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  file:
    path: /app/telemetry_output/telemetry_data.jsonl # Path inside the collector container

processors:
  batch:
    send_batch_size: 100
    timeout: 10s
  resource: # Add consistent resource attributes for the Collector's own metrics if needed
    attributes:
      - key: environment
        value: development
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
