receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  file:
    path: /app/telemetry_output/telemetry_data.jsonl
  debug:
    verbosity: detailed

processors:
  batch:
    send_batch_size: 100
    timeout: 1s
  resource:
    attributes:
      - key: environment
        value: development
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
